# Generated by Django 4.1.4 on 2022-12-30 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0003_sense_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sense',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
