# Generated by Django 4.1.4 on 2023-01-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0006_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='activity60',
            new_name='activity0',
        ),
    ]
